baseURL = 'https://rbdetailing.netlify.app/'
languageCode = 'en-us'
paginate = 6
theme= "coHub"
title = 'RB AutoDetailing'


  # Main Menu

  [[menu.Main]]
  name = "Pricing"
  url= "#pricing"
  weight = 5

  [[menu.Main]]
  name = "Book Now"
  url= "/contact/"
  weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1

  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
  # theme_overrides = "css/overrides.css"
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} <a href=\"./\" target=\"_blank\">RB AutoDetailing </a>"
  fabFormURL =  "https://fabform.io/f/u00kv3-"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/logo.png"
  footerlogo = "images/logo.png"
  footerDescription = "Bringing premium mobile detailing directly to your doorstep."

  [params.address]
  address = "West London, UK"
  email = "Autodetailingrb@gmail.com"
  openingDesc = "Give us a call or drop by anytime, we endeavour to answer all enquiries within 24 hours on business days."
  openingHours = "We are open from 7am — 7pm week days."
  phone = "+447472863216"

  [params.map]
  enabled = false
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "51.30"
  longitude = "-0.07"
  pinImage = "images/pin.png"

  # Social icons
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/rb_auto_detailing_ltd/"
  weight = 1
